# Generated by Django 3.0.5 on 2020-04-05 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='type_of_picture',
            field=models.CharField(choices=[('OP', 'Portes et Fenêtres'), ('BS', 'Bibliothèques'), ('DR', 'Dressings')], default='OP', max_length=2),
        ),
    ]
