# Generated by Django 3.0.5 on 2020-04-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200405_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titre',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='type_of_picture',
            new_name="type d'image",
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date de publication'),
        ),
    ]
