# Generated by Django 3.0.5 on 2020-04-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200405_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name="type d'image",
            new_name='type_image',
        ),
    ]
